version: "3"

vars:
  TAILWIND_CMD:
    sh: command -v tailwindcss >/dev/null 2>&1 && echo "tailwindcss" || echo "npx tailwindcss@latest"

tasks:
  templ:
    desc: Run templ with integrated server and hot reload
    cmds:
      - templ generate --watch --proxy="http://localhost:8080" --cmd="go run ./cmd/server/main.go" --open-browser=false

  tailwind:
    desc: Watch Tailwind CSS changes
    cmds:
      - "{{.TAILWIND_CMD}} -i ./assets/css/input.css -o ./assets/css/output.css --watch"

  dev:
    desc: Start development server with hot reload
    cmds:
      - task --parallel tailwind templ

  test:acceptance:
    desc: Run acceptance tests
    cmds:
      - go test ./tests/acceptance/... -v -timeout 120s

  test:acceptance:short:
    desc: Run acceptance tests with shorter timeout
    cmds:
      - go test ./tests/acceptance/... -v -timeout 60s

  test:acceptance:watch:
    desc: Run acceptance tests in watch mode (requires entr or similar)
    cmds:
      - find tests/acceptance -name "*.go" | entr -c go test ./tests/acceptance/... -v -timeout 120s
