package memory

import placesAdapters "bitmerchant/internal/places/adapters"

type MemorySessionRestaurantVisitRepository = placesAdapters.MemoryVisitRepository

var NewMemorySessionRestaurantVisitRepository = placesAdapters.NewMemoryVisitRepository
